### ISSUE TITLE
Duration vs FiniteDuration

### ISSUE THREAD

**Issue by ceedubs** [Verizon/knobs#33]
As far as I can tell, there's no way to put an [infinite duration](http://www.scala-lang.org/api/2.10.4/#scala.concurrent.duration.Duration$$Infinite) as a value in a knobs config file. Therefore it seems to me like `CfgDuration` should wrap a `FiniteDuration` instead of a `Duration`. This would make it so that consumers don't have to tell the compiler "trust me, this is going to be a finite value".

If this isn't changed, I think knobs should at least provide a `Configured[FiniteDuration]` instance that returns `None` if the duration is infinite.

Either way I'm happy to submit a PR -- I just wanted to get some feedback on which approach is preferred.

cc @runarorama @timperrett

**Comment by ceedubs** [comment]
I guess another possibility is providing a special "infinity" (or something) value that can be put in the config for an infinite duration.

**Comment by runarorama** [comment]
I think it's reasonable to assume that `FiniteDuration` was intended here instead of `Duration`. I can't think of an instance where you'd want to configure an infinite duration using Knobs.

**Comment by timperrett** [comment]
@ceedubs sounds fine to me.

**Comment by ceedubs** [comment]
I'm going to consider this resolved after #38.
