### ISSUE TITLE
List of nested objects

### ISSUE THREAD

**Issue by i-am-the-slime** [Verizon/knobs#37]
How would I go about reading something like this:

```
something = [{ 
    key1 = "yay",
    key2 = "yoi"
  },
 { 
    key1 = "food",
    key2 = "insurmountable"
  },
]
```

?

**Comment by runarorama** [comment]
How about:

```
something {
    one { 
      key1 = "yay"
      key2 = "yoi"
    }
    two { 
      key1 = "food"
      key2 = "insurmountable"
    }
}
```

**Comment by i-am-the-slime** [comment]
I want to read the list independently of its length. That's my current state:
```scala
  implicit val _configuredMap:Configured[Map[TokenName, List[Scope]]] =
    new Configured[Map[TokenName, List[Scope]]] {
      override def apply(v: CfgValue): Option[Map[TokenName, List[Scope]]] = {
        implicitly[Configured[List[(String, List[String])]]].apply(v).map(
          _.map{ case (k, vs) => (TokenName(k), vs.map(Scope)) }.toMap
        )
      }
    }
```

**Comment by runarorama** [comment]
A crucial thing to note here is that a `Config` is really just a map from names to `Configured` values. There is no nesting, and that's very much on purpose. Knobs is not a recursive data structure. This serves a couple of purposes:

1. To keep Knobs as simple as possible.
2. To prevent "config creep". It's likely that your nested data structure wants to be Scala code.

That said, you can always turn any portion of a `Config` into a map:

``` scala
def cfgMap(at: String)[A:Configured](c: Config): Map[TokenName, A] =
  (c subconfig at).env.map {
    case (k, v) => (TokenName(k), v.convertTo[A])
  }
```

**Comment by timperrett** [comment]
@i-am-the-slime i would also refer you to this comment, which i think its still appropriate :-) https://github.com/Verizon/knobs/issues/23#issuecomment-222748383 - we typically don't load this kind of data via the config.

**Comment by i-am-the-slime** [comment]
Thanks guys, I think it makes sense to not have it be a dynamic list in my case. So I did it as Runar suggested.
