### ISSUE TITLE
Document versioning strategy

### ISSUE THREAD

**Issue by ceedubs** [Verizon/knobs#40]
Knobs has a couple notable aspects to its versioning strategy:
- It uses traditional semantic versioning, which is different than most major scala libs.
- It uses an `a` suffix convention. I think this is based on which version of scalaz-stream it depends on, but I'm not sure that I totally understand it.

This versioning strategy should be documented.

**Comment by rossabaker** [comment]
The scalaz-suffixed crossbuilds are on their way out with knobs-5 and cats-1.
