### ISSUE TITLE
Can't lookup Duration from Typesafe config

### ISSUE THREAD

**Issue by ceedubs** [Verizon/knobs#44]
It looks like internally Typesafe config is storing durations in a stringy fashion. So when Typesafe config is converted to knobs config, it becomes a `CfgText` as opposed to a `CfgDuration`. And then when you try to look it up as a `Duration`, you get a `None` instead of the actual value.

Unfortunately, I don't know of any way that you could solve this within the typesafe module itself, unless you proactively attempt to parse every String value as a duration and fall back to string if that doesn't work which sounds really gross and not necessarily what's desired.

One other option is to have the `Configured[Duration]` instance attempt to parse the `CfgText` value if that's what it gets instead of `CfgDuration`. I think that this could solve the problem without really being harmful. The only downsides that I can think of are that it is a change to `core` that is really meant to support `typesafe` and that it is just a little less simple than the current approach.

Example below.

```scala
scala> import com.typesafe.config.ConfigFactory, scala.concurrent.duration.Duration
import com.typesafe.config.ConfigFactory
import scala.concurrent.duration.Duration

scala> val ts = ConfigFactory.parseString(""" "dur" = 3 seconds """)
ts: com.typesafe.config.Config = Config(SimpleConfigObject({"dur":"3 seconds"}))

scala> ts.getDuration("dur", java.util.concurrent.TimeUnit.MILLISECONDS)
res0: Long = 3000

scala> val k = knobs.Typesafe.config(ts).run // YOLO
k: knobs.Config = Config(Map(dur -> CfgText(3 seconds)))

scala> k.lookup[Duration]("dur")
res1: Option[scala.concurrent.duration.Duration] = None

scala> k.lookup[String]("dur")
res2: Option[String] = Some(3 seconds)
```

**Comment by rossabaker** [comment]
Is there a parser for the Typesafe Duration format outside of Typesafe Config?  How do we get from CfgText to a Duration outside the Typesafe module?

**Comment by ceedubs** [comment]
@rossabaker I don't know, but I just looked at how Typesafe Config is doing it, and I don't think that it's going to make you feel any better: https://github.com/lightbend/config/blob/aa6958469aa022e7a27bd08463062a28a5c02d75/config/src/main/java/com/typesafe/config/impl/SimpleConfig.java#L705

**Comment by rossabaker** [comment]
Do we want `.lookup[Duration]` on a String in a knobs-native config to return a `Duration` if it's formatted right?  If so, how about a `.lookup[Int]`?  How far do we go blurring the line between `String` and `Duration`?

**Comment by ceedubs** [comment]
@rossabaker I'm not sure -- it's tricky. To be honest I don't really have a horse in this race anymore, so I don't have a strong opinion on this, and people can feel free to close out this issue.
