### ISSUE TITLE
2.12 release

### ISSUE THREAD

**Issue by reactormonk** [Verizon/knobs#45]
I'd guess you'd need a 2.12 version of https://github.com/Verizon/sbt-rig beforehand, I'm hitting

    [warn]  Note: Unresolved dependencies path:
    [warn]          org.scalatest:scalatest_2.12:2.2.6 ((verizon.build.common) RigPlugin.scala#L79)
    [warn]            +- io.verizon.knobs:knobs_2.12:3.11.0-SNAPSHOT
    [warn]          org.scalacheck:scalacheck_2.12:1.12.5 ((verizon.build.common) RigPlugin.scala#L79)
    [warn]            +- io.verizon.knobs:knobs_2.12:3.11.0-SNAPSHOT
    [warn]          org.scoverage:scalac-scoverage-runtime_2.12:1.1.1 ((scoverage.ScoverageSbtPlugin) ScoverageSbtPlugin.scala#L30)
    [warn]            +- io.verizon.knobs:knobs_2.12:3.11.0-SNAPSHOT
    [warn]          org.scoverage:scalac-scoverage-plugin_2.12:1.1.1 ((scoverage.ScoverageSbtPlugin) ScoverageSbtPlugin.scala#L30)
    [warn]            +- io.verizon.knobs:knobs_2.12:3.11.0-SNAPSHOT

**Comment by timperrett** [comment]
@reactormonk yeah we have not even looked 2.12 yet. It's not the rig plugin itself that needs upgrading (that's an SBT thing), rather, it just needs to know how to support 2.12... should be an easy fix if you want to give it a go?

**Comment by reactormonk** [comment]
From what I see, I'd have to up a few versions, since there are no 2.12 releases of these - should I do that globally, or figure out how to do that for 2.12 only?

**Comment by timperrett** [comment]
@reactormonk Presumably it would have to be conditionally, just like we load the scalatest / scalacheck stuff already. Likewise with the compiler flags - we are specialized per scala version.
