### ISSUE TITLE
String substitution not working

### ISSUE THREAD

**Issue by cquiroz** [Verizon/knobs#53]
I'm trying to import files using string substitution but it seems it is not working as in the documentation

If I for example do this

```
web-server {
    import "$(user.home)/test.cfg"
}
```

I get an exception saying 
```
java.io.FileNotFoundException: /home/software/seqexec_server_gs_test-0.2.0/conf/$(user.home)/test.cfg (No such file or directory)
```

The same happens if I use `$(HOME)`

Should this work?

**Comment by rossabaker** [comment]
I can reproduce this and see that we're not doing any interpolation of import directives.  I do believe this should work, since it's the import example in the docs.

I got it working in #54, but that ticket needs further discussion.
