### ISSUE TITLE
fs2 streams?

### ISSUE THREAD

**Issue by ZizhengTai** [Verizon/knobs#55]
Is it possible to replace scalaz streams with fs2 streams, considering that many libraries are now moving toward the cats/fs2 ecosystem?

**Comment by vegansk** [comment]
:+1:

**Comment by timperrett** [comment]
@rossabaker was looking into this a little while back, but im not sure where it ended up.

**Comment by rossabaker** [comment]
I put that on the backburner because the version of fs2 that everybody is using is a milestone and we don't have a great milestone story ourselves.  I would like to move on this when fs2-0.10 is released, which is expected after cats-1.0.

**Comment by adelbertc** [comment]
https://github.com/Verizon/knobs/pull/57

**Comment by rossabaker** [comment]
Fixed by #57.
