### ISSUE TITLE
Documentation: usage.md

### ISSUE THREAD

**Issue by daddykotex** [Verizon/knobs#56]
Hi,

I found an error in the documentation. I was about to open a PR to update the doc, but the file is already up to date with the Maven Central repository information. Maybe the docs just need to be regenerated.

https://verizon.github.io/knobs/usage is the page where I found the invalid information.

Thanks.

**Comment by timperrett** [comment]
They probally just need re-publishing- will look :)

**Comment by timperrett** [comment]
Pushed and updated. @rossabaker we should probally update knobs to our new doc format with hugo and the new sbt plugin.
